name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.3'
        channel: 'stable'
        cache: true
        
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Run tests
      run: flutter test
      
    - name: Analyze code
      run: flutter analyze
      
    - name: Build Windows app
      run: flutter build windows --release
      
    - name: Create release archive
      id: build_archive
      env:
        VERSION_INPUT: ${{ github.event.inputs.version }}
      run: |
        $version = if ($env:GITHUB_REF -match 'refs/tags/(.+)') { $matches[1] } else { $env:VERSION_INPUT }
        $archiveName = "api-utility-flutter-$version-windows.zip"
        
        # Create archive with the built app
        Compress-Archive -Path "build\windows\x64\runner\Release\*" -DestinationPath $archiveName -Force
        
        # Set output for next step
        echo "ARCHIVE_NAME=$archiveName" >> $env:GITHUB_OUTPUT
        echo "VERSION=$version" >> $env:GITHUB_OUTPUT
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.build_archive.outputs.VERSION || github.ref_name }}
        name: API Utility Flutter ${{ steps.build_archive.outputs.VERSION || github.ref_name }}
        body: |
          ## API Utility Flutter ${{ steps.build_archive.outputs.VERSION || github.ref_name }}
          
          ### What's New
          - Automated release build
          - Windows desktop application
          
          ### Installation
          1. Download the `api-utility-flutter-${{ steps.build_archive.outputs.VERSION || github.ref_name }}-windows.zip` file
          2. Extract the archive to your desired location
          3. Run `api_utility_flutter.exe`
          
          ### System Requirements
          - Windows 10 or later
          - Visual C++ Redistributable (if not already installed)
          
          ### Changes
          See the commit history for detailed changes.
        draft: false
        prerelease: false
        files: ${{ steps.build_archive.outputs.ARCHIVE_NAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
